### ISSUE TITLE
XCUITest/Screenshot support?

### ISSUE THREAD

**Issue by viktorbenei** [BinaryBirds/Testify#1]
Just curious if you plan to support UI Test screenshots, so that the test case can be linked to the related screenshot in case you'd want to check the UI at the time of the test case.

**Comment by tib** [comment]
This tool is just a pure XCTest -> JSON converter, but yes I have other long term plans & ideas, with limited free time. 😃 My main goal here would be to provide diagnostics, test results and code coverage reports mostly for server side Swift (both linux & macOS) projects.

**Comment by viktorbenei** [comment]
Yeah, you don't have to tell me about limited free time 😅Hope you'll have some time, but regardless just wanted to ask if it's planned, I was just curious 😉

**Comment by tib** [comment]
So the final answer is no, this is not coming into Testify. (Maybe as a standalone tool)

**Comment by viktorbenei** [comment]
Makes sense - thank you!
